import type { InspectorCatalog } from '../types/inspector';

export const INSPECTOR_CATALOG: InspectorCatalog = {
  robotTypes: [
    { id: 'table_arm', label: 'Table robot arm', description: 'Fixed-base manipulator for tabletop tasks.' },
    { id: 'mobile_manipulator', label: 'Mobile manipulator', description: 'Base + arm for warehouse and lab navigation.' },
    { id: 'warehouse_picker', label: 'Warehouse picker', description: 'High-throughput pick-and-place in structured aisles.' },
    { id: 'drone_inspection', label: 'Drone inspection', description: 'Aerial platform for scan and inspect missions.' },
    { id: 'humanoid_upper', label: 'Humanoid upper body', description: 'Dual-arm humanoid torso for dexterous manipulation.' },
    { id: 'rover_arm', label: 'Rover arm', description: 'Field rover with mounted manipulator.' },
    { id: 'custom', label: 'Custom robot', description: 'User-defined kinematics and end-effector stack.' },
  ],
  gripperTypes: [
    { id: 'parallel_jaw', label: 'Parallel jaw' },
    { id: 'vacuum', label: 'Vacuum cup' },
    { id: 'soft_gripper', label: 'Soft gripper' },
    { id: 'magnetic', label: 'Magnetic' },
    { id: 'tool_changer', label: 'Tool changer' },
  ],
  taskTypes: [
    { id: 'pick_object', label: 'Pick up object', description: 'Grasp and lift a target object.' },
    { id: 'move_to_target', label: 'Move to target', description: 'Transport object to a goal zone.' },
    { id: 'stack_blocks', label: 'Stack blocks', description: 'Place objects in a vertical stack.' },
    { id: 'open_drawer', label: 'Open drawer', description: 'Pull handle and open articulated furniture.' },
    { id: 'inspect_object', label: 'Inspect object', description: 'Orient sensor over object for QA.' },
    { id: 'sort_objects', label: 'Sort objects', description: 'Classify and bin items by type.' },
    { id: 'recover_grasp', label: 'Recover failed grasp', description: 'Re-plan after slip or misalignment.' },
    { id: 'navigate_target', label: 'Navigate to target', description: 'Drive base to waypoint before manipulation.' },
    { id: 'avoid_obstacle', label: 'Avoid obstacle', description: 'Re-route around occluders or hazards.' },
    { id: 'scan_environment', label: 'Scan environment', description: 'Capture splat or depth coverage pass.' },
    { id: 'assemble_object', label: 'Assemble simple object', description: 'Mate parts with contact constraints.' },
  ],
  taskExamples: [
    { id: 'ex_pick', label: 'Pick up the mug when handle is hidden', taskType: 'pick_object' },
    { id: 'ex_move', label: 'Move object to marked goal zone', taskType: 'move_to_target' },
    { id: 'ex_stack', label: 'Stack three blocks by size', taskType: 'stack_blocks' },
    { id: 'ex_drawer', label: 'Open top drawer without collision', taskType: 'open_drawer' },
    { id: 'ex_inspect', label: 'Inspect label on shipping box', taskType: 'inspect_object' },
    { id: 'ex_sort', label: 'Sort red and blue parts into bins', taskType: 'sort_objects' },
    { id: 'ex_recover', label: 'Recover grasp after slip', taskType: 'recover_grasp' },
    { id: 'ex_nav', label: 'Navigate to shelf waypoint', taskType: 'navigate_target' },
    { id: 'ex_avoid', label: 'Avoid occluder while reaching', taskType: 'avoid_obstacle' },
    { id: 'ex_scan', label: 'Scan tabletop for splat coverage', taskType: 'scan_environment' },
    { id: 'ex_assemble', label: 'Insert peg into hole', taskType: 'assemble_object' },
  ],
  targetObjects: ['mug', 'block', 'bowl', 'drawer', 'box', 'tool', 'part', 'bin', 'occluder'],
  difficulties: ['easy', 'medium', 'hard', 'adversarial'],
  controlModes: ['autonomous', 'teleop', 'assisted', 'replay'],
  safetyModes: ['strict', 'standard', 'research'],
};
