import type { CurriculumState } from '../../lib/types/inspector';
import { SectionSourceBar } from '../shared/DataHonesty';
import { InspectorBadge, InspectorCard, InspectorEmpty, InspectorField, InspectorListItem } from './shared';

interface CurriculumPanelProps {
  curriculum: CurriculumState;
  onToggleVariation: (id: string) => void;
}

export function CurriculumPanel({ curriculum, onToggleVariation }: CurriculumPanelProps) {
  return (
    <div className="inspector-panel-stack">
      <SectionSourceBar meta={curriculum.meta} />
      <InspectorCard hint="Variations generated by the practice loop after a failed attempt." title="Variation ladder">
        <InspectorField label="Failure focus" value={curriculum.failureFocus} />
        <div className="inspector-inline-badges">
          {curriculum.difficultyLadder.map((step) => (
            <InspectorBadge key={step} label={step} tone="neutral" />
          ))}
        </div>
      </InspectorCard>

      <InspectorCard hint="From run data — selection is local only until training worker is wired." title="Generated variations">
        {curriculum.variations.length ? (
          curriculum.variations.map((variation) => (
            <InspectorListItem
              key={variation.id}
              meta={`${variation.difficulty} · ${variation.transformSummary}`}
              onClick={() => onToggleVariation(variation.id)}
              title={variation.label}
              trailing={
                <InspectorBadge
                  label={variation.selected ? 'selected' : 'skip'}
                  tone={variation.selected ? 'accent' : 'neutral'}
                />
              }
            />
          ))
        ) : (
          <InspectorEmpty message="Run a failed attempt to generate curriculum variants." />
        )}
      </InspectorCard>

      <InspectorCard hint="External training worker not connected yet." title="Training actions">
        <p className="inspector-callout">
          Generate more and Apply curriculum require a training worker endpoint — not wired yet.
        </p>
        <div className="inspector-action-row">
          <button
            className="secondary-button"
            disabled
            title="POST /training/generate not implemented"
            type="button"
          >
            Generate more
          </button>
          <button
            className="primary-button"
            disabled
            title="POST /training/apply not implemented"
            type="button"
          >
            Apply curriculum
          </button>
        </div>
      </InspectorCard>
    </div>
  );
}
